spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/data/data #영구 저장
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none #create-drop
